/*
 * Generated by the Jasper component of Apache Tomcat
 * Version: Apache Tomcat/10.1.17
 * Generated at: 2024-10-02 09:05:12 UTC
 * Note: The last modified time of this file was set to
 *       the last modified time of the source file after
 *       generation to assist with modification tracking.
 */
package org.apache.jsp.base_002dcomponent;

import jakarta.servlet.*;
import jakarta.servlet.http.*;
import jakarta.servlet.jsp.*;

public final class footer_jsp extends org.apache.jasper.runtime.HttpJspBase
    implements org.apache.jasper.runtime.JspSourceDependent,
                 org.apache.jasper.runtime.JspSourceImports,
                 org.apache.jasper.runtime.JspSourceDirectives {

  private static final jakarta.servlet.jsp.JspFactory _jspxFactory =
          jakarta.servlet.jsp.JspFactory.getDefaultFactory();

  private static java.util.Map<java.lang.String,java.lang.Long> _jspx_dependants;

  private static final java.util.Set<java.lang.String> _jspx_imports_packages;

  private static final java.util.Set<java.lang.String> _jspx_imports_classes;

  static {
    _jspx_imports_packages = new java.util.HashSet<>();
    _jspx_imports_packages.add("jakarta.servlet");
    _jspx_imports_packages.add("jakarta.servlet.http");
    _jspx_imports_packages.add("jakarta.servlet.jsp");
    _jspx_imports_classes = null;
  }

  private volatile jakarta.el.ExpressionFactory _el_expressionfactory;
  private volatile org.apache.tomcat.InstanceManager _jsp_instancemanager;

  public java.util.Map<java.lang.String,java.lang.Long> getDependants() {
    return _jspx_dependants;
  }

  public java.util.Set<java.lang.String> getPackageImports() {
    return _jspx_imports_packages;
  }

  public java.util.Set<java.lang.String> getClassImports() {
    return _jspx_imports_classes;
  }

  public boolean getErrorOnELNotFound() {
    return false;
  }

  public jakarta.el.ExpressionFactory _jsp_getExpressionFactory() {
    if (_el_expressionfactory == null) {
      synchronized (this) {
        if (_el_expressionfactory == null) {
          _el_expressionfactory = _jspxFactory.getJspApplicationContext(getServletConfig().getServletContext()).getExpressionFactory();
        }
      }
    }
    return _el_expressionfactory;
  }

  public org.apache.tomcat.InstanceManager _jsp_getInstanceManager() {
    if (_jsp_instancemanager == null) {
      synchronized (this) {
        if (_jsp_instancemanager == null) {
          _jsp_instancemanager = org.apache.jasper.runtime.InstanceManagerFactory.getInstanceManager(getServletConfig());
        }
      }
    }
    return _jsp_instancemanager;
  }

  public void _jspInit() {
  }

  public void _jspDestroy() {
  }

  public void _jspService(final jakarta.servlet.http.HttpServletRequest request, final jakarta.servlet.http.HttpServletResponse response)
      throws java.io.IOException, jakarta.servlet.ServletException {

    if (!jakarta.servlet.DispatcherType.ERROR.equals(request.getDispatcherType())) {
      final java.lang.String _jspx_method = request.getMethod();
      if ("OPTIONS".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        return;
      }
      if (!"GET".equals(_jspx_method) && !"POST".equals(_jspx_method) && !"HEAD".equals(_jspx_method)) {
        response.setHeader("Allow","GET, HEAD, POST, OPTIONS");
        response.sendError(HttpServletResponse.SC_METHOD_NOT_ALLOWED, "JSPs only permit GET, POST or HEAD. Jasper also permits OPTIONS");
        return;
      }
    }

    final jakarta.servlet.jsp.PageContext pageContext;
    jakarta.servlet.http.HttpSession session = null;
    final jakarta.servlet.ServletContext application;
    final jakarta.servlet.ServletConfig config;
    jakarta.servlet.jsp.JspWriter out = null;
    final java.lang.Object page = this;
    jakarta.servlet.jsp.JspWriter _jspx_out = null;
    jakarta.servlet.jsp.PageContext _jspx_page_context = null;


    try {
      response.setContentType("text/html;charset=UTF-8");
      pageContext = _jspxFactory.getPageContext(this, request, response,
      			null, true, 8192, true);
      _jspx_page_context = pageContext;
      application = pageContext.getServletContext();
      config = pageContext.getServletConfig();
      session = pageContext.getSession();
      out = pageContext.getOut();
      _jspx_out = out;

      out.write("\r\n");
      out.write("<!-- Footer Section -->\r\n");
      out.write("<footer class=\"footer\">\r\n");
      out.write("    <div class=\"container\">\r\n");
      out.write("        <div class=\"row\">\r\n");
      out.write("            <!-- About Section -->\r\n");
      out.write("            <div class=\"col-md-2 footer-section\">\r\n");
      out.write("                <h5>About</h5>\r\n");
      out.write("                <p>Nam nec tellus ac odio tincidunt auctor a ornare odio.</p>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Company Section -->\r\n");
      out.write("            <div class=\"col-md-2 footer-section\">\r\n");
      out.write("                <h5>Company</h5>\r\n");
      out.write("                <a href=\"#\">Delivery</a><br>\r\n");
      out.write("                <a href=\"#\">Legal Notice</a><br>\r\n");
      out.write("                <a href=\"#\">About Us</a><br>\r\n");
      out.write("                <a href=\"#\">Sitemap</a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Profile Section -->\r\n");
      out.write("            <div class=\"col-md-2 footer-section\">\r\n");
      out.write("                <h5>Profile</h5>\r\n");
      out.write("                <a href=\"#\">Address</a><br>\r\n");
      out.write("                <a href=\"#\">Authentication</a><br>\r\n");
      out.write("                <a href=\"#\">History</a><br>\r\n");
      out.write("                <a href=\"#\">Pricesdrop</a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Customer Service Section -->\r\n");
      out.write("            <div class=\"col-md-3 footer-section\">\r\n");
      out.write("                <h5>Customer Service</h5>\r\n");
      out.write("                <p>Phone: +123.456.789</p>\r\n");
      out.write("                <a href=\"#\">Contact</a><br>\r\n");
      out.write("                <a href=\"#\">My Account</a><br>\r\n");
      out.write("                <a href=\"#\">Stores</a>\r\n");
      out.write("            </div>\r\n");
      out.write("\r\n");
      out.write("            <!-- Newsletter Signup Section -->\r\n");
      out.write("            <div class=\"col-md-3 footer-section\">\r\n");
      out.write("                <h5>Newsletter Signup</h5>\r\n");
      out.write("                <p>You may unsubscribe at any moment. For that purpose, please find our contact info in the legal notice.</p>\r\n");
      out.write("                <div class=\"newsletter-signup\">\r\n");
      out.write("                    <input type=\"email\" placeholder=\"Your email...\" />\r\n");
      out.write("                    <button>&rarr;</button>\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("\r\n");
      out.write("    <!-- Footer Bottom -->\r\n");
      out.write("    <div class=\"footer-bottom\">\r\n");
      out.write("        <div class=\"container\">\r\n");
      out.write("            <div class=\"row justify-content-between align-items-center\">\r\n");
      out.write("                <div class=\"col-md-6 text-center text-md-left\">\r\n");
      out.write("                    <span class=\"copyright\">Copyright &copy; Freeze Clothing Store | Powered by Group 2</span>\r\n");
      out.write("                </div>\r\n");
      out.write("                <div class=\"col-md-6 text-center text-md-right\">\r\n");
      out.write("                    <!-- Payment Icons -->\r\n");
      out.write("                    <img src=\"https://upload.wikimedia.org/wikipedia/commons/5/57/Visa_2021.svg\" alt=\"Visa\">\r\n");
      out.write("                    <img src=\"https://upload.wikimedia.org/wikipedia/commons/thumb/0/04/Mastercard-logo.png/800px-Mastercard-logo.png\" alt=\"MasterCard\">\r\n");
      out.write("                    <img src=\"https://upload.wikimedia.org/wikipedia/commons/5/5a/Discover_Card_logo.png\" alt=\"Discover\">\r\n");
      out.write("                    <img src=\"https://upload.wikimedia.org/wikipedia/commons/4/41/Amazon_Pay_logo_2017.png\" alt=\"Amazon\">\r\n");
      out.write("                </div>\r\n");
      out.write("            </div>\r\n");
      out.write("        </div>\r\n");
      out.write("    </div>\r\n");
      out.write("</footer>\r\n");
    } catch (java.lang.Throwable t) {
      if (!(t instanceof jakarta.servlet.jsp.SkipPageException)){
        out = _jspx_out;
        if (out != null && out.getBufferSize() != 0)
          try {
            if (response.isCommitted()) {
              out.flush();
            } else {
              out.clearBuffer();
            }
          } catch (java.io.IOException e) {}
        if (_jspx_page_context != null) _jspx_page_context.handlePageException(t);
        else throw new ServletException(t);
      }
    } finally {
      _jspxFactory.releasePageContext(_jspx_page_context);
    }
  }
}
